version: '3.4'
services:
  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui
  #   restart: always

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    restart: always


  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    # command: sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'" # -e ${RAILS_ENV}
    depends_on:
      - postgres
      - redis
      # - sidekiq
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      # - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      BUNDLE_PATH: /gems
      GEM_PATH: /gems
      GEM_HOME: /gems
      TZ: America/New_York
  postgres:
    image: postgres:14.5
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/mysql

  # sidekiq:
  #   depends_on:
  #     - mysql
  #     - redis
  #   build: .
  #   command: sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec sidekiq"
  #   volumes:
      # - .:/app
  #     - gem_cache:/usr/local/bundle/gems
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #     TZ: America/New_York

  # solargraph:
  #   build: .
  #   command: sh -c "bundle install && bundle exec solargraph socket --host=0.0.0.0 --port=7658"
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     # - gem_documentation:/home/ruby/.yard
  #   ports:
  #   - '7658:7658'


# Names our volume
volumes:
  db-data:
  gem_cache:
